apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
# to assign minikube tunnel to external address, check this issue for mac os https://github.com/kubernetes/minikube/issues/14039
