# metadata contains labels
# spec contains selectors

apiVersion: apps/v1
kind: Deployment # kind of service
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec: # specification for deployment
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: # applies to a pod
      labels:
        app: nginx
    spec: # blueprint for pod
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
